name: zola 
version: 0.20.0
summary: A fast static site generator in a single binary with everything built-in.
description: |
  A fast static site generator in a single binary with everything built-in.
  https://www.getzola.org

base: core18
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  zola:
    command: zola
    plugs:
      - home
      - network
      - network-bind

parts:
  zola:
    source-type: git
    source: https://github.com/getzola/zola.git
    source-tag: v0.20.0
    plugin: rust
    rust-channel: stable
    build-packages:
    - build-essential
    - cmake
    - libssl-dev
    - pkg-config
