#!/usr/bin/env python3
"""Generate a paper's figures from committed artifacts.

Charts in a paper are generated, never drawn, so that a number on an axis cannot
drift from the JSON it came from. Output is deterministic SVG with no external
dependencies — the repository's Python tooling is stdlib-only — and every file
carries its provenance in a comment: input artifact, generator, command.

A figure is declared in the paper's `figures/figures.toml`:

    [[figure]]
    name = "wall-time"
    kind = "grouped-bars"
    title = "Wall time, baseline vs current"
    source = "benchmarks/results/<hw>/ab/<file>.json"
    series = ["a_median", "b_median"]
    labels = ["baseline", "current"]
    metric = "wall_s"
    unit = "s"

Usage:
    scripts/papers/figures.py <paper-dir>          # regenerate all figures
    scripts/papers/figures.py <paper-dir> --check  # fail if any is stale
"""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPERS = ROOT / "docs" / "papers"

W, H = 900, 420
PAD_L, PAD_R, PAD_T, PAD_B = 190, 24, 46, 54
COLOURS = ("#9aa5b1", "#2f6f4f")


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def grouped_bars(spec: dict, data: dict) -> str:
    """Horizontal grouped bars, one group per site, one bar per series."""
    metric = spec["metric"]
    sites = list(data["sites"].keys())
    series = spec["series"]
    labels = spec.get("labels", series)
    unit = spec.get("unit", "")

    values = [[float(data["sites"][s][metric][k]) for k in series] for s in sites]
    vmax = max(max(v) for v in values) or 1.0

    plot_w = W - PAD_L - PAD_R
    plot_h = H - PAD_T - PAD_B
    group_h = plot_h / max(len(sites), 1)
    bar_h = group_h / (len(series) + 0.8)

    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
        f'viewBox="0 0 {W} {H}" font-family="ui-sans-serif, system-ui, sans-serif">',
        f"<!-- generated by scripts/papers/figures.py from {spec['source']} -->",
        f"<!-- command: scripts/dev.sh papers figures <paper-dir> -->",
        f'<rect width="{W}" height="{H}" fill="#ffffff"/>',
        f'<text x="{PAD_L}" y="26" font-size="15" font-weight="600" fill="#111">'
        f"{esc(spec['title'])}</text>",
    ]

    # legend
    lx = W - PAD_R
    for i, lab in reversed(list(enumerate(labels))):
        lx -= 12 + 7 * len(lab) + 16
        out.append(f'<rect x="{lx}" y="16" width="10" height="10" fill="{COLOURS[i % 2]}"/>')
        out.append(
            f'<text x="{lx + 15}" y="25" font-size="11" fill="#444">{esc(lab)}</text>'
        )

    for gi, site in enumerate(sites):
        gy = PAD_T + gi * group_h
        out.append(
            f'<text x="{PAD_L - 10}" y="{gy + group_h / 2 + 4}" font-size="11.5" '
            f'text-anchor="end" fill="#222">{esc(site)}</text>'
        )
        for si in range(len(series)):
            v = values[gi][si]
            bw = plot_w * (v / vmax)
            by = gy + 0.25 * bar_h + si * bar_h
            out.append(
                f'<rect x="{PAD_L}" y="{by:.1f}" width="{bw:.1f}" height="{bar_h * 0.86:.1f}" '
                f'fill="{COLOURS[si % 2]}"/>'
            )
            out.append(
                f'<text x="{PAD_L + bw + 6:.1f}" y="{by + bar_h * 0.66:.1f}" font-size="10.5" '
                f'fill="#333">{v:,.0f}{unit}</text>'
                if vmax > 100
                else f'<text x="{PAD_L + bw + 6:.1f}" y="{by + bar_h * 0.66:.1f}" '
                f'font-size="10.5" fill="#333">{v:,.2f}{unit}</text>'
            )

    out.append(
        f'<line x1="{PAD_L}" y1="{PAD_T}" x2="{PAD_L}" y2="{H - PAD_B}" stroke="#ccc"/>'
    )
    note = spec.get("note", "")
    if note:
        out.append(
            f'<text x="{PAD_L}" y="{H - 18}" font-size="10.5" fill="#666">{esc(note)}</text>'
        )
    out.append("</svg>")
    return "\n".join(out) + "\n"


def simple_bars(spec: dict, _data: dict | None) -> str:
    """Bars from literal values declared in the figure spec itself.

    For results that no benchmark JSON holds — process footprints read with
    `footprint -p`, for instance. The values live in the spec so that the
    figure and `measurements.toml` can be checked against each other by review.
    """
    rows = spec["rows"]
    unit = spec.get("unit", "")
    vmax = max(float(r["value"]) for r in rows) or 1.0
    h = PAD_T + PAD_B + 46 * len(rows)
    plot_w = W - PAD_L - PAD_R

    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{h}" '
        f'viewBox="0 0 {W} {h}" font-family="ui-sans-serif, system-ui, sans-serif">',
        "<!-- generated by scripts/papers/figures.py from values declared in figures.toml -->",
        f'<rect width="{W}" height="{h}" fill="#ffffff"/>',
        f'<text x="{PAD_L}" y="26" font-size="15" font-weight="600" fill="#111">'
        f"{esc(spec['title'])}</text>",
    ]
    for i, r in enumerate(rows):
        y = PAD_T + i * 46
        v = float(r["value"])
        bw = plot_w * (v / vmax)
        colour = r.get("colour", COLOURS[1] if i == len(rows) - 1 else COLOURS[0])
        out.append(
            f'<text x="{PAD_L - 10}" y="{y + 22}" font-size="11.5" text-anchor="end" '
            f'fill="#222">{esc(r["label"])}</text>'
        )
        out.append(f'<rect x="{PAD_L}" y="{y + 6}" width="{bw:.1f}" height="24" fill="{colour}"/>')
        out.append(
            f'<text x="{PAD_L + bw + 8:.1f}" y="{y + 23}" font-size="11" fill="#333">'
            f"{v:,.0f}{unit}</text>"
        )
    note = spec.get("note", "")
    if note:
        out.append(f'<text x="{PAD_L}" y="{h - 16}" font-size="10.5" fill="#666">{esc(note)}</text>')
    out.append("</svg>")
    return "\n".join(out) + "\n"


KINDS = {"grouped-bars": grouped_bars, "simple-bars": simple_bars}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paper", help="paper directory name or path")
    ap.add_argument("--check", action="store_true", help="fail if a figure is stale")
    args = ap.parse_args()

    d = Path(args.paper)
    if not d.is_dir():
        d = PAPERS / args.paper
    # Accept a relative path from anywhere; report paths against the repo root.
    d = d.resolve()
    spec_path = d / "figures" / "figures.toml"
    if not spec_path.is_file():
        print(f"no figure spec at {spec_path}", file=sys.stderr)
        return 1
    with spec_path.open("rb") as fh:
        doc = tomllib.load(fh)

    stale = []
    for spec in doc.get("figure", []):
        kind = spec.get("kind")
        if kind not in KINDS:
            print(f"unknown figure kind `{kind}`", file=sys.stderr)
            return 1
        data = None
        if spec.get("source"):
            src = ROOT / spec["source"]
            if not src.is_file():
                print(f"missing source artifact: {spec['source']}", file=sys.stderr)
                return 1
            data = json.loads(src.read_text(encoding="utf-8"))
        svg = KINDS[kind](spec, data)
        out = d / "figures" / f"{spec['name']}.svg"
        if args.check:
            if not out.is_file() or out.read_text(encoding="utf-8") != svg:
                stale.append(out.name)
        else:
            out.write_text(svg, encoding="utf-8")
            print(f"wrote {out.relative_to(ROOT)}")

    if args.check:
        if stale:
            print(f"stale figures: {', '.join(stale)}", file=sys.stderr)
            return 1
        print("figures are current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
