#!/usr/bin/env python3
"""Integrity checks and status index for the `PERF-*` backlog.

Source of truth:

* `docs/performance/HOTSPOTS.md` — the summary table defines every `PERF-*` item
  (id, location, priority) and is the only place an item may be introduced.
* `docs/performance/OPTIMIZATIONS.md` — append-only log; an item is *done* when
  it has a `## PERF-NNN` section there, and that section must cite a commit.

Everything else (this index, cross-references in other documents) is derived.

Usage:
    scripts/dev/perf_index.py check      # validate the backlog, exit 1 on error
    scripts/dev/perf_index.py generate   # rewrite docs/performance/STATUS.md
    scripts/dev/perf_index.py json       # machine-readable dump on stdout
    scripts/dev/perf_index.py open       # the open items, one bullet each
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

# ZOLA_DEV_ROOT lets the tooling tests point the checker at a fixture tree.
ROOT = Path(os.environ.get("ZOLA_DEV_ROOT", Path(__file__).resolve().parents[2]))
PERF_DOCS = ROOT / "docs" / "performance"
HOTSPOTS = PERF_DOCS / "HOTSPOTS.md"
OPTIMIZATIONS = PERF_DOCS / "OPTIMIZATIONS.md"
STATUS = PERF_DOCS / "STATUS.md"

GENERATED_BANNER = (
    "<!-- Generated by scripts/dev/perf_index.py — do not edit by hand.\n"
    "     Edit HOTSPOTS.md / OPTIMIZATIONS.md and run `scripts/dev.sh generate`. -->"
)

# PERF-001, PERF-005a — the optional letter marks a sub-item of a parent record.
ID_RE = re.compile(r"\bPERF-(\d{3})([a-z])?\b")

COMPONENTS = (
    sorted(p.name for p in (ROOT / "components").iterdir() if p.is_dir())
    if (ROOT / "components").is_dir()
    else []
)


@dataclass
class Item:
    id: str
    location: str
    component: str
    priority: str
    status: str = "open"
    commit: str = ""
    subitems: list[str] = field(default_factory=list)


def _component_of(location: str) -> str:
    """Map a HOTSPOTS location string to a workspace component, if it names one."""
    for token in re.findall(r"[A-Za-z_][A-Za-z0-9_/.-]*", location):
        head = token.split("/")[0]
        if head in COMPONENTS:
            return head
    return "—"


def parse_hotspots(text: str) -> dict[str, Item]:
    """Read the summary table. Rows look like `| PERF-001 | \\`path\\` | … | P0 |`."""
    items: dict[str, Item] = {}
    for line in text.splitlines():
        if not line.startswith("| PERF-"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        ident = cells[0]
        location = cells[1].replace("`", "").strip()
        priority = cells[-1].strip("*")
        items[ident] = Item(
            id=ident,
            location=location,
            component=_component_of(location),
            priority=priority,
        )
    return items


def parse_optimizations(text: str) -> dict[str, str]:
    """Map completed item id -> cited commit subject (empty string if absent)."""
    done: dict[str, str] = {}
    current = None
    for line in text.splitlines():
        heading = re.match(r"^##\s+(PERF-\d{3}[a-z]?)\b", line)
        if heading:
            current = heading.group(1)
            done[current] = ""
            continue
        if current and line.startswith("**Commit.**"):
            done[current] = line[len("**Commit.**") :].strip().strip("`")
    return done


def collect_references() -> dict[str, set[str]]:
    """Every `PERF-*` mention in tracked markdown, keyed by id."""
    refs: dict[str, set[str]] = {}
    roots = [ROOT / "docs", ROOT / ".claude", ROOT / "CLAUDE.md", ROOT / "AGENTS.md"]
    files: list[Path] = []
    for r in roots:
        if r.is_file():
            files.append(r)
        elif r.is_dir():
            files.extend(p for p in r.rglob("*.md") if "content" not in p.parts)
    for path in files:
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for num, suffix in ID_RE.findall(text):
            refs.setdefault(f"PERF-{num}{suffix or ''}", set()).add(
                str(path.relative_to(ROOT))
            )
    return refs


def build() -> tuple[dict[str, Item], list[str]]:
    """Return (items, errors). Every error string names its own fix."""
    errors: list[str] = []

    if not HOTSPOTS.is_file():
        return {}, [f"{HOTSPOTS.relative_to(ROOT)} is missing; the PERF backlog has no source of truth."]

    items = parse_hotspots(HOTSPOTS.read_text(encoding="utf-8"))
    if not items:
        errors.append(
            f"{HOTSPOTS.relative_to(ROOT)} contains no `| PERF-NNN | …` summary rows.\n"
            "    Every backlog item must have a row in the summary table."
        )

    done = parse_optimizations(
        OPTIMIZATIONS.read_text(encoding="utf-8") if OPTIMIZATIONS.is_file() else ""
    )
    for ident, commit in done.items():
        parent = ident[:8]  # PERF-005a -> PERF-005
        target = items.get(ident) or items.get(parent)
        if target is None:
            errors.append(
                f"{OPTIMIZATIONS.name} documents {ident}, but no such item is defined in "
                f"{HOTSPOTS.name}.\n"
                f"    Add a summary-table row for {ident}, or correct the heading."
            )
            continue
        if ident != target.id:
            target.subitems.append(ident)
        target.status = "done"
        target.commit = commit or target.commit
        if not commit:
            errors.append(
                f"{OPTIMIZATIONS.name}: {ident} has no `**Commit.**` line.\n"
                "    A completed item must cite the commit that delivered it."
            )

    for ident, where in sorted(collect_references().items()):
        parent = ident[:8]
        if ident in items or parent in items:
            continue
        errors.append(
            f"{ident} is referenced by {', '.join(sorted(where))} but is not defined in "
            f"{HOTSPOTS.name}.\n"
            f"    Add a summary-table row for {ident}, or remove the reference."
        )

    return items, errors


def render(items: dict[str, Item]) -> str:
    open_items = [i for i in items.values() if i.status == "open"]
    done_items = [i for i in items.values() if i.status == "done"]
    lines = [
        GENERATED_BANNER,
        "",
        "# PERF backlog status",
        "",
        f"{len(done_items)} done, {len(open_items)} open. "
        "Definitions live in `HOTSPOTS.md`, results in `OPTIMIZATIONS.md`.",
        "",
        "| ID | Component | Location | Priority | Status | Commit |",
        "| -- | --------- | -------- | -------- | ------ | ------ |",
    ]
    for item in sorted(items.values(), key=lambda i: i.id):
        ident = item.id
        if item.subitems:
            ident += " (" + ", ".join(sorted(item.subitems)) + ")"
        lines.append(
            f"| {ident} | {item.component} | `{item.location}` | {item.priority} | "
            f"{item.status} | {item.commit or '—'} |"
        )
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    command = argv[1] if len(argv) > 1 else "check"
    items, errors = build()

    if command == "json":
        json.dump(
            {i.id: i.__dict__ for i in sorted(items.values(), key=lambda x: x.id)},
            sys.stdout,
            indent=2,
        )
        print()
        return 1 if errors else 0

    if command == "open":
        for item in sorted(items.values(), key=lambda i: i.id):
            if item.status == "open":
                print(f"* {item.id} ({item.priority}, {item.component}) {item.location}")
        return 0

    if command == "generate":
        if errors:
            print("perf backlog is inconsistent; refusing to generate STATUS.md:\n")
            for e in errors:
                print(f"  - {e}")
            return 1
        STATUS.write_text(render(items), encoding="utf-8")
        print(f"wrote {STATUS.relative_to(ROOT)}")
        return 0

    if command == "check":
        expected = render(items) if not errors else None
        if expected is not None:
            actual = STATUS.read_text(encoding="utf-8") if STATUS.is_file() else ""
            if actual != expected:
                errors.append(
                    f"{STATUS.relative_to(ROOT)} is out of date.\n"
                    "    Run:\n"
                    "        scripts/dev.sh generate"
                )
        if errors:
            print("PERF backlog check FAILED:\n")
            for e in errors:
                print(f"  - {e}")
            return 1
        print(f"PERF backlog OK ({len(items)} items).")
        return 0

    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
