#!/usr/bin/env python3
"""Generate and verify the workspace component map.

Sources of truth:

* `components/*/Cargo.toml` and the root `Cargo.toml` — dependencies, features,
  test and bench targets.
* `scripts/dev/components.toml` — the facts a manifest cannot express: what each
  component is responsible for, and which dependency edges are forbidden.

Output: `docs/architecture/COMPONENTS.md`, which is checked in so that a reader
(or a fresh agent session) can orient without running anything, and checked in CI
so it can never drift from the manifests.

Usage:
    scripts/dev/repo_map.py check      # invariants + drift, exit 1 on failure
    scripts/dev/repo_map.py generate   # rewrite docs/architecture/COMPONENTS.md
    scripts/dev/repo_map.py json       # machine-readable dump on stdout
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:  # pragma: no cover - depends on the interpreter
    print(
        f"this script needs Python 3.11 or newer for tomllib; "
        f"you are running {sys.version.split()[0]} ({sys.executable}).\n"
        "    Install a newer python3, or skip this check — it is not needed to "
        "build or test Zola.",
        file=sys.stderr,
    )
    raise SystemExit(2)

# ZOLA_DEV_ROOT lets the tooling tests point the generator at a fixture workspace.
ROOT = Path(os.environ.get("ZOLA_DEV_ROOT", Path(__file__).resolve().parents[2]))
META = ROOT / "scripts" / "dev" / "components.toml"
OUT = ROOT / "docs" / "architecture" / "COMPONENTS.md"

GENERATED_BANNER = (
    "<!-- Generated by scripts/dev/repo_map.py — do not edit by hand.\n"
    "     Edit the crate manifests or scripts/dev/components.toml,\n"
    "     then run `scripts/dev.sh generate`. -->"
)


@dataclass
class Component:
    name: str
    responsibility: str = ""
    perf_notes: str = ""
    deps: list[str] = field(default_factory=list)
    dev_deps: list[str] = field(default_factory=list)
    dependents: list[str] = field(default_factory=list)
    features: list[str] = field(default_factory=list)
    tests: list[str] = field(default_factory=list)
    benches: list[str] = field(default_factory=list)
    layer: int = 0
    perf_items: list[str] = field(default_factory=list)


def load() -> tuple[dict[str, Component], dict]:
    meta = tomllib.loads(META.read_text(encoding="utf-8"))
    names = sorted(p.name for p in (ROOT / "components").iterdir() if p.is_dir())
    known = set(names)

    comps: dict[str, Component] = {}
    for name in names:
        path = ROOT / "components" / name
        manifest = tomllib.loads((path / "Cargo.toml").read_text(encoding="utf-8"))
        spec = meta.get("component", {}).get(name, {})
        comps[name] = Component(
            name=name,
            responsibility=spec.get("responsibility", ""),
            perf_notes=spec.get("perf_notes", ""),
            deps=sorted(k for k in manifest.get("dependencies", {}) if k in known),
            dev_deps=sorted(
                k for k in manifest.get("dev-dependencies", {}) if k in known
            ),
            features=sorted(manifest.get("features", {})),
            # tests/common.rs is a shared helper module, not a test target.
            tests=sorted(
                p.name for p in (path / "tests").glob("*.rs") if p.name != "common.rs"
            )
            if (path / "tests").is_dir()
            else [],
            benches=sorted(p.name for p in (path / "benches").glob("*.rs"))
            if (path / "benches").is_dir()
            else [],
        )

    for name, comp in comps.items():
        for dep in comp.deps:
            comps[dep].dependents.append(name)
    for comp in comps.values():
        comp.dependents.sort()

    return comps, meta


def assign_layers(comps: dict[str, Component]) -> list[str]:
    """Longest-path layering over normal dependencies. Returns cycle errors."""
    errors: list[str] = []
    state: dict[str, int] = {}
    visiting: list[str] = []

    def depth(name: str) -> int:
        if name in state:
            return state[name]
        if name in visiting:
            cycle = " -> ".join(visiting[visiting.index(name) :] + [name])
            errors.append(
                f"dependency cycle in the workspace: {cycle}\n"
                "    Break the cycle; the crate graph must stay a DAG."
            )
            return 0
        visiting.append(name)
        d = max((depth(dep) + 1 for dep in comps[name].deps), default=0)
        visiting.pop()
        state[name] = d
        return d

    for name in comps:
        comps[name].layer = depth(name)
    return errors


def check_invariants(comps: dict[str, Component], meta: dict) -> list[str]:
    errors = assign_layers(comps)

    declared = set(meta.get("component", {}))
    actual = set(comps)
    for missing in sorted(actual - declared):
        errors.append(
            f"component `{missing}` has no entry in scripts/dev/components.toml.\n"
            f"    Add [component.{missing}] with a one-line `responsibility`."
        )
    for stale in sorted(declared - actual):
        errors.append(
            f"scripts/dev/components.toml describes `{stale}`, which no longer exists.\n"
            f"    Remove [component.{stale}]."
        )
    for name, comp in comps.items():
        if name in declared and not comp.responsibility:
            errors.append(
                f"component `{name}` has an empty `responsibility` in components.toml.\n"
                "    One sentence: what does this crate own?"
            )

    for rule in meta.get("invariants", {}).get("forbidden", []):
        src, dst = rule["from"], rule["to"]
        if src in comps and dst in comps[src].deps:
            errors.append(
                f"forbidden dependency `{src}` -> `{dst}`: {rule['reason']}\n"
                f"    Either remove the dependency, or change the rule in "
                f"scripts/dev/components.toml and say why in the commit message."
            )
    return errors


def perf_items_by_component() -> dict[str, list[str]]:
    """Open PERF-* items grouped by component, via scripts/dev/perf_index.py."""
    script = Path(__file__).resolve().parent / "perf_index.py"
    if not script.is_file() or not (ROOT / "docs" / "performance").is_dir():
        return {}
    try:
        out = subprocess.run(
            [sys.executable, str(script), "json"],
            capture_output=True,
            text=True,
            cwd=ROOT,
        ).stdout
        items = json.loads(out)
    except (OSError, json.JSONDecodeError):
        return {}
    grouped: dict[str, list[str]] = {}
    for item in items.values():
        if item.get("status") == "open" and item.get("component") in ("", "—", None):
            continue
        if item.get("status") == "open":
            grouped.setdefault(item["component"], []).append(item["id"])
    return {k: sorted(v) for k, v in grouped.items()}


def render(comps: dict[str, Component]) -> str:
    perf = perf_items_by_component()
    for name, comp in comps.items():
        comp.perf_items = perf.get(name, [])

    ordered = sorted(comps.values(), key=lambda c: (c.layer, c.name))
    lines = [
        GENERATED_BANNER,
        "",
        "# Workspace components",
        "",
        "The `zola` binary in `src/` is a thin CLI over the crates below. A crate may",
        "only depend on crates in a lower layer; the layer number is the longest",
        "dependency path to a leaf, computed from the manifests.",
        "",
        "| Layer | Component | Responsibility |",
        "| ----- | --------- | -------------- |",
    ]
    for c in ordered:
        lines.append(f"| {c.layer} | `{c.name}` | {c.responsibility} |")

    lines += [
        "",
        "## Dependencies",
        "",
        "| Component | Depends on | Used by | Features |",
        "| --------- | ---------- | ------- | -------- |",
    ]
    for c in ordered:
        deps = ", ".join(f"`{d}`" for d in c.deps) or "—"
        if c.dev_deps:
            deps += " (dev: " + ", ".join(f"`{d}`" for d in c.dev_deps) + ")"
        used = ", ".join(f"`{d}`" for d in c.dependents) or "the `zola` binary"
        feats = ", ".join(f"`{f}`" for f in c.features) or "—"
        lines.append(f"| `{c.name}` | {deps} | {used} | {feats} |")

    lines += [
        "",
        "## Tests and benchmarks",
        "",
        "Unit tests live next to the code in every crate; the table lists the",
        "integration-test and benchmark targets, which is what you run to exercise a",
        "component end to end.",
        "",
        "| Component | Integration tests | Benchmarks |",
        "| --------- | ----------------- | ---------- |",
    ]
    for c in ordered:
        if not c.tests and not c.benches:
            continue
        tests = (
            ", ".join(f"`cargo test -p {c.name} --test {t[:-3]}`" for t in c.tests)
            or "—"
        )
        benches = ", ".join(f"`{b}`" for b in c.benches) or "—"
        lines.append(f"| `{c.name}` | {tests} | {benches} |")

    hot = [c for c in ordered if c.perf_notes or c.perf_items]
    if hot:
        lines += [
            "",
            "## Performance-sensitive components",
            "",
            "Open `PERF-*` items are derived from `docs/performance/HOTSPOTS.md`.",
            "",
            "| Component | Why it matters | Open PERF items |",
            "| --------- | -------------- | --------------- |",
        ]
        for c in hot:
            lines.append(
                f"| `{c.name}` | {c.perf_notes or '—'} | "
                f"{', '.join(c.perf_items) or '—'} |"
            )

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    command = argv[1] if len(argv) > 1 else "check"
    comps, meta = load()
    errors = check_invariants(comps, meta)

    if command == "json":
        json.dump({n: c.__dict__ for n, c in sorted(comps.items())}, sys.stdout, indent=2)
        print()
        return 1 if errors else 0

    if command == "generate":
        if errors:
            print("architecture invariants are violated; refusing to generate:\n")
            for e in errors:
                print(f"  - {e}")
            return 1
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(render(comps), encoding="utf-8")
        print(f"wrote {OUT.relative_to(ROOT)}")
        return 0

    if command == "check":
        if not errors:
            expected = render(comps)
            actual = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
            if actual != expected:
                errors.append(
                    f"{OUT.relative_to(ROOT)} is out of date.\n"
                    "    Run:\n"
                    "        scripts/dev.sh generate"
                )
        if errors:
            print("architecture check FAILED:\n")
            for e in errors:
                print(f"  - {e}")
            return 1
        print(f"architecture OK ({len(comps)} components, no forbidden edges).")
        return 0

    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
